[supabase]
url = "https://qqdcstapxntmepgzxiil.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZGNzdGFweG50bWVwZ3p4aWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3OTU0ODcsImV4cCI6MjA4NTM3MTQ4N30.GU64_v3R1zS0_yLZNT52xekCfd8fT83pdGruUSkRSGc"
# Required for Text-to-SQL Chatbot
db_url = "postgresql://postgres.qqdcstapxntmepgzxiil:qw8WXwZdreLHCpnT@aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres"


[ocr_space]
api_key = "K84153240588957"

[groq]
api_key = "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"
