[supabase]
url = https://qqdcstapxntmepgzxiil.supabase.co
key = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxZGNzdGFweG50bWVwZ3p4aWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3OTU0ODcsImV4cCI6MjA4NTM3MTQ4N30.GU64_v3R1zS0_yLZNT52xekCfd8fT83pdGruUSkRSGc

[google]
api_key = AIzaSyCz3ctBMima3jgPBS9JsFkeUf6cir0IKKM

[supabase]
# Required for Text-to-SQL Chatbot
db_url = "postgresql://postgres.qqdcstapxntmepgzxiil:[qw8WXwZdreLHCpnT]@aws-1-ap-southeast-

